### ISSUE TITLE
No API to send a message and error at the same time

### ISSUE THREAD

**Issue by RobotK** [rollbar/rollbar-apple#105]
We currently use `+ (void)log:(RollbarLevel)level message:(NSString*)message exception:(NSException*)exception data:(NSDictionary*)data` to send both a message and an exception to rollbar at the same time, but in the new API there doesn't seem to be an equivalent method. 

Ideally, we'd like to be able to send a message along with a swift Error and optional data dictionary.

**Comment by akornich** [comment]
@RobotK , you may want to look at these APIs:

`+ (void)log:(RollbarLevel)level
    message:(nonnull NSString *)message
       data:(nullable NSDictionary<NSString *, id> *)data
    context:(nullable NSString *)context;
+ (void)log:(RollbarLevel)level
  exception:(nonnull NSException *)exception
       data:(nullable NSDictionary<NSString *, id> *)data
    context:(nullable NSString *)context;
+ (void)log:(RollbarLevel)level
      error:(nonnull NSError *)error
       data:(nullable NSDictionary<NSString *, id> *)data
    context:(nullable NSString *)context;`

They allow to send a message-, NSException-, and NSError-like content/payloads to Rollbar. Where `context` can be an extra string message. As well as custom data dictionary could be provided.

Is that what you are looking for?

**Comment by akornich** [comment]
Then, try using:

+ (void)log:(RollbarLevel)level
      error:(nonnull NSError *)error
       data:(nullable NSDictionary<NSString *, id> *)data
    context:(nullable NSString *)context;

Place your message as the value for `context` parameter.
