### ISSUE TITLE
ARM64 slice excluded from cocoapods spec?

### ISSUE THREAD

**Issue by lavenj** [rollbar/rollbar-apple#109]
Hi! Looks like this library is still stripping the arm64 slice when building for the simulator, which causes issues when building for the simulator on an M1* mac.

Wondering if it would be possible to update the pod to include the required slice?

following podspec lines would need to be removed:
```
    s.pod_target_xcconfig  = { "ONLY_ACTIVE_ARCH" => "YES", "EXCLUDED_ARCHS[sdk=iphonesimulator*]" => "arm64" }
    s.user_target_xcconfig = { "ONLY_ACTIVE_ARCH" => "YES", "EXCLUDED_ARCHS[sdk=iphonesimulator*]" => "arm64" }

    s.tvos.pod_target_xcconfig  = { "ONLY_ACTIVE_ARCH" => "YES", "EXCLUDED_ARCHS[sdk=appletvsimulator*]" => "arm64" }
    s.tvos.user_target_xcconfig = { "ONLY_ACTIVE_ARCH" => "YES", "EXCLUDED_ARCHS[sdk=appletvsimulator*]" => "arm64" }
```

Background is here:

https://github.com/CocoaPods/CocoaPods/issues/10978#issuecomment-933567488
and
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io/66233165#66233165

**Comment by keagan** [comment]
curious where this is on the roadmap @akornich, as today is *presumably* the last day of 2022-Q1. thnx

**Comment by atetlaw** [comment]
+1 for this, since the pod spec uses `user_target_xcconfig` it pollutes all the project configs through inheritance. I'm currently using `post_install` to read in every `xcconfig` and remove the line. 

The guide mentions this and says its use is not recommended: https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig

**Comment by jessesquires** [comment]
Another +1 — just want to share that this is also a problem for my projects.

**Comment by akornich** [comment]
Guys, thanks for all the feedback. Let me see if I can squeeze it in within the next couple of weeks...

**Comment by lavenj** [comment]
Appreciated, thank you!
