### ISSUE TITLE
RollbarPLCrashReporter.init() no longer available

### ISSUE THREAD

**Issue by francisli** [rollbar/rollbar-apple#136]
**Describe the bug**
After upgrading to the latest RollbarSwift/Notifier/PLCrashReporter 2.0.3, I received the following error upon building:

```
.../AppDelegate.swift:52:37: 'init()' has been explicitly marked unavailable here (RollbarPLCrashReporter.RollbarPLCrashCollector)
```

This is evident in the macro annotations in the RollbarCrashCollectorBase.h:

```
@interface RollbarCrashCollectorBase : NSObject<RollbarCrashCollector> {
    @private
    id<RollbarCrashCollectorObserver> _observer;
}

/// Designated initializer.
/// @param observer a crash collector observer.
- (instancetype)initWithObserver:(nullable id<RollbarCrashCollectorObserver>)observer
NS_DESIGNATED_INITIALIZER;

/// Hides parametrless initializer.
- (instancetype)init
NS_UNAVAILABLE;

@end
```

Is the expected usage now to initialize with a null observer as follows? If so, then the documentation must be updated.

```
        ...
        let rollbarCrashCollector = RollbarPLCrashCollector(observer: nil)
        Rollbar.initWithConfiguration(rollbarConfig, crashCollector: rollbarCrashCollector)
```

**Rollbar-Apple SDK version: v2.0.3**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other:

**Comment by akornich** [comment]
@francisli , thanks for letting us know. 
Yes, please, use the available initializer passing `nil` into it. 
I already have a fix in. And it will be available within v2.1.0 (most likely in a couple of days).
