### ISSUE TITLE
Is it thread safe on iOs?

### ISSUE THREAD

**Issue by RSATom** [rollbar/rollbar-apple#172]
I get crash very similar to https://github.com/rollbar/rollbar-ios/issues/245#issuecomment-699420886 pretty frequently with v2.2.4

**Comment by akornich** [comment]
@RSATom, please, make sure you are not sharing logger instances across different threads.

**Comment by RSATom** [comment]
I'm using new Swift concurrency with `async`/`await` and `actors` and flow can switch to different thread after any `await`. But even in that case in should be safe, since access to Rollbar object happens only from a single thread at any specific moment. But I still seen crashes. Finally I've moved all access to Rollbar to `@MainActor` but today got crash again... Right now I'm trying to find if there any other threading issue in my code...

**Comment by RSATom** [comment]
I've disabled Rollbar, and there is no crash anymore for a long time...

**Comment by rollbar-bborsits** [comment]
Hey @RSATom, We released major bugfixes above 3.0. This should work properly now, so I am closing this issue for now. Feel free to reopen it if you still experience any issue.

**Comment by RSATom** [comment]
@rollbar-bborsits thank you, but unfortunately we was not able to wait so long time and already switched to different solution...

**Comment by rollbar-bborsits** [comment]
@RSATom I understand your decision, and thanks for sharing it openly. Do you mind sharing which solution you switched to and its strengths? We want to learn where we fall short so that we can improve. Thanks.

**Comment by RSATom** [comment]
@rollbar-bborsits it's https://bugfender.com
The main reason was inability to use Rollbar on iOs platform due to crashes.
Other good thing in Bugfender - it's possible to look events in order they happens. To get the same with Rollbar I have to use RQL. By default Rollbar orders events by second boundary and within specific second order of events is almost random, but in worst cases it's required to see events in right order.

But just to be clear, we are still using Rollbar on other platforms. I mean it's not so bad...

**Comment by RSATom** [comment]
Other thing I would like to see in Rollbar - ability to filter events from specific user/device by time interval.
