### ISSUE TITLE
Rollbar crashes when device runs out of memory

### ISSUE THREAD

**Issue by okalentiev** [rollbar/rollbar-apple#176]
**Describe the bug**
It looks like `RollbarLogger.m` contains code that is using deprecated [writeData:](https://developer.apple.com/documentation/foundation/nsfilehandle/1410936-writedata) method that does not handle errors gracefully. Therefore when the device runs out of space, the method throws an exception. 

Here is the crash report from the Crashlytics. 
```
*** -[NSConcreteFileHandle writeData:]: No space left on device

Fatal Exception: NSFileHandleOperationException
0  CoreFoundation                 0x91d3c __exceptionPreprocess
1  libobjc.A.dylib                0x146a8 objc_exception_throw
2  Foundation                     0x125264 -[NSConcreteFileHandle offsetInFile]
3  Foundation                     0x5dff0 -[NSConcreteFileHandle writeData:]
4  RollbarNotifier                0xf164 -[RollbarLogger queuePayload_OnlyCallOnThread:] + 736 (RollbarLogger.m:736)
5  Foundation                     0x3a868 __NSThreadPerformPerform
6  CoreFoundation                 0xb22b0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
7  CoreFoundation                 0xc22d8 __CFRunLoopDoSource0
8  CoreFoundation                 0x5678 __CFRunLoopDoSources0
9  CoreFoundation                 0xaaa8 __CFRunLoopRun
10 CoreFoundation                 0x1de1c CFRunLoopRunSpecific
11 Foundation                     0x173dc -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
12 RollbarNotifier                0x1925c -[RollbarThread run] + 71 (RollbarThread.m:71)
13 Foundation                     0x638bc __NSThread__start__
14 libsystem_pthread.dylib        0x63a4 _pthread_start
15 libsystem_pthread.dylib        0x49fc thread_start
```

**To Reproduce**
I didn't try to reproduce the error, but I think that if there's a way to fill up the simulator space, it is possible to trigger the error. 

**Expected behavior**
App should not crash

**Rollbar-Apple SDK version: v2.0.3**

**Calling the SDK from (x-mark all suitable):**
- [ ] Objective-C
- [x] Swift
- [ ] Other: 

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS iOS 15.3.1

**Comment by akornich** [comment]
@okalentiev , thanks for reporting it!
