### ISSUE TITLE
Doc and examples out of date

### ISSUE THREAD

**Issue by technomage** [rollbar/rollbar-apple#18]
I attempted to follow the docs to install. 

1.12 did not compile when added as a swift package manager dependency. 

2.0.0-alpha27 only defines RollbarCommon and RollbarDeploys, both docs and examples reference Rollbar and RollbarConfig not defined in those packages.

**Comment by akornich** [comment]
@technomage , Rollbar-Apple SDK is a big rework of Rollbar-iOS and is not backward compatible with Rollbar-iOS. Please, see details here: https://github.com/rollbar/rollbar-apple/wiki
`Rollbar` and `RollbarConfig` classes are defined as part of RollbarNotifier package.
 I assume you are referring to the following documentation https://docs.rollbar.com/docs/apple. It is by no means complete but it is definitely up to date as far as describing how to start with basic usage of this SDK (https://docs.rollbar.com/docs/apple#using-sdk-in-your-code).
The SDK is in the alpha phase now and we are actively preparing for its transition to the beta within (probably) the next few weeks. The docs will be expanded with more details describing more advanced usage scenarios during this time and while in beta.
For users already familiar with Rollbar-iOS it will be relatively easy to recognize some similarities and parallels with Rollbar-iOS concepts that did change in Rollbar-Apple mainly as a better repackaging of the familiar concepts with some naming changes that are more appropriate in general and when using the SDK from Swift specifically.
So, if you are willing to give it a try, please, do so. I'll be glad to assist you closely. We are looking for user feedback regarding the new SDK API  now and during beta.

**Comment by akornich** [comment]
BTW, regarding examples, please, disregard for now any content of the repo/Examples folder. These are the old sample apps that were brought over from Rollbar-iOS and will be shortly adopted to actually use Rollbar-Apple.
The only proper sample apps are the ones located within repo/Demos folder and are part of the main SDK development workspace: https://github.com/rollbar/rollbar-apple/tree/master/RollbarSDK.xcworkspace

**Comment by akornich** [comment]
closing due to no response
