### ISSUE TITLE
Issue/clarification on iOS crash traces

### ISSUE THREAD

**Issue by jamiepmullan** [rollbar/rollbar-apple#207]
**Describe the bug**
I'm trying to integrate Rollbar into an iOS (Obj-C) app to help track crashes. However struggling to get it to report into Rollbar properly.

My setup is as follows (following the docs):
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Rollbar
    RollbarConfig *config = [RollbarConfig new];
    config.destination.accessToken = @"abcdef";
    config.destination.environment = @"prod";
    id<RollbarCrashCollector> crashCollector = [[RollbarPLCrashCollector alloc] init];
    [Rollbar initWithConfiguration:config crashCollector:crashCollector];
```

Rollbar lib versions:
```
    pod "RollbarNotifier", "~> 2.3.3"
    pod "RollbarDeploys", "~> 2.3.3"
    pod "RollbarPLCrashReporter", "~> 2.3.3"
```

I am trying to replicate a crash using:
```
[NSException raise:@"Invalid foo value" format:@"foo is invalid"];
```

I have turned off "Debugging" from Xcode just incase it was capturing it before the Rollbar SDK.

All I'm getting in Rollbar on the web is (at an info level):
```
The app was exited at the end of last session.
```

I would have thought it would have sent the stack trace to Rollbar?
Have I missed something?

Following this:
https://docs.rollbar.com/docs/apple#optionally-define-a-crash-report-collector-instance

Tried to look for examples, but they were all over 2 years old so not sure how applicable they would be with Rollbar's new Apple lib.
https://github.com/rollbar/rollbar-apple/tree/master/Examples

**Calling the SDK from (x-mark all suitable):**
[X] Objective-C
[] Swift
[] Other:

**Comment by akornich** [comment]
Hi @jamiepmullan , it looks like you did all the expected SDK hookup correctly.
Please, make sure all the proper filters are on within the Rollbar Dashboard (website). Crash reports are coming with Critical RolbarLevel.
Also, please, keep in mind that the crash reports will be picked up and reported to Rollbar.com on the next subsequent application startup after the crash (assuming the crash does not happen before the Rollbar was properly initialized with a valid config and a crash reporter module).
Feel free to let me know here if those suggestions did not resolve the problem.

Yes, the Examples are from the SDK's previous incarnation (as Rollbar-iOS) and eventually will be adopted for this SDK. You should be able to find up-to-date examples within [Demos](https://github.com/rollbar/rollbar-apple/tree/master/Demos). All the Demos are parts of the [Xcode workspace for the SDK](https://github.com/rollbar/rollbar-apple/tree/master/RollbarSDK.xcworkspace). If you clone the repo and open the workspace in Xcode the Demos will be available within the Xcode and can be built and debugged individually right there.

**Comment by akornich** [comment]
@akornich , when you select that Error alert with (unknown) title on the RollbarDashboard and open up the latest occurrence of it, do you see a Raw Crash Report on the occurrence details page? [Somewhat similar to this one...](https://rollbar.com/akornich/RollbarSDKs/items/393/occurrences/251499988906/)

**Comment by akornich** [comment]
@jamiepmullan , that is good news. Did you have dSYM for the build uploaded to the project?
If you have this message above the raw crash report:

This backtrace could not be symbolicated because a matching dSYM upload was not present
View the dSYM uploads received for this project [here](https://rollbar.com/akornich/RollbarSDKs/settings/dsym/). Check out the [docs](https://github.com/rollbar/rollbar-ios/blob/master/README.md) for help in setting up iOS symbolication.

please, follow the instructions within the links of that message.

Once dSYM is uploaded, new reports should be symbolicated and titles of new occurrences should be updated when the symbolication succeeds.

**Comment by jamiepmullan** [comment]
@akornich ah! that might be it... interestingly 1 worked without having the dSYM uploaded...
Thanks for helping me clear that up.

**Comment by akornich** [comment]
@jamiepmullan , please, keep me posted on the outcome. By the way, the item title will not be updated even when the occurrence titles get fixed since the item title is based on the very first occurrence grouped into an item...

**Comment by akornich** [comment]
@jamiepmullan , can we close this item? or, are you still having some problems?
