### ISSUE TITLE
Breaking changes in the API in 2.4.0 from #236 causes builds to fail

### ISSUE THREAD

**Issue by doublerebel** [rollbar/rollbar-apple#243]
**Describe the bug**
Breaking changes in the API in [2.4.0](https://github.com/rollbar/rollbar-apple/releases/tag/2.4.0) from #236 causes builds to fail at compile time

**To Reproduce**
1. Build with any version from 2.0.0 - 2.3.4
2. Success
3. Build with 2.4.0

**Expected behavior**
The API to not change in a minor release version

**Screenshots**
```
 /Users/[REDACTED]/:19:28: cannot assign to property: 'accessToken' is a get-only property
        config.destination.accessToken = "[REDACTED]"
^
❌  /Users/[REDACTED]/:20:28: cannot assign to property: 'environment' is a get-only property
        config.destination.environment = Configuration.environment.rawValue
        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
❌  /Users/[REDACTED]/:21:33: cannot assign to property: 'suppressSdkInfoLogging' is a get-only property
        config.developerOptions.suppressSdkInfoLogging = true
        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
❌  /Users/[REDACTED]/:22:17: type 'Rollbar' has no member 'updateConfiguration'
        Rollbar.updateConfiguration(config)
        ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
❌  /Users/[REDACTED]/:30:16: cannot assign to property: 'person' is a get-only property
        config.person = RollbarPerson(id: userId.description, email: email)
        ~~~~~~~ ^~~~~~~~~~~~~~~~~~~
❌  /Users/[REDACTED]/:31:17: type 'Rollbar' has no member 'updateConfiguration'
        Rollbar.updateConfiguration(config)
        ~~~~~~~^~~~~~
```

**Rollbar-Apple SDK version: v.2.4.0**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: iPhone
 - OS: iOS
 - OS version: N/A
 
**Smartphone (please complete the following information):**
N/A - compile-time error

**Additional context**
We have been using the ~same APIs for several versions since **rollbar-ios**.  We love Rollbar, use it all the time!  Just wanted to report as soon as we saw it in CI today.

**Comment by matux** [comment]
3.x is out!

This is the recommended version of our Rollbar Apple SDK as it fixes a litany of bugs and incorporates new features that simplify and improve error and crash detection!
