### ISSUE TITLE
Rate limiting isn't handled correctly which results into more requests to be sent

### ISSUE THREAD

**Issue by ExtremeMan** [rollbar/rollbar-apple#255]
Rollbar has a project setting which allows to limit amount of requests to be processed on the backend. When this limit is hit, backend responds with `429` http status code and header fields indicating remaining limit and when this limit will be reset (in case if it is hit).

Example of backend response when limits are hit:
```
Response: <NSHTTPURLResponse: 0x2832d0280> { URL: https://api.rollbar.com/api/1/item/ } { Status Code: 429, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Content-Length" =     (
        94
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Fri, 27 Jan 2023 20:21:48 GMT"
    );
    Etag =     (
        "W/\"5e-cTpwgLUgfG9co8DdJdWtew\""
    );
    Server =     (
        "nginx/1.17.9"
    );
    Via =     (
        "1.1 google"
    );
    "access-control-allow-credentials" =     (
        true
    );
    "alt-svc" =     (
        "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
    );
    "x-rate-limit-limit" =     (
        50000
    );
    "x-rate-limit-remaining" =     (
        0
    );
    "x-rate-limit-remaining-seconds" =     (
        66988
    );
    "x-rate-limit-reset" =     (
        1674917896
    );
    "x-response-time" =     (
        "2.927ms"
    );
} }
```

As you can see backend response with correct status code `429`, provided correct `x-rate-limit-remaining` and `x-rate-limit-remaining-seconds` values for client library to properly delay any further requests to be attempted.

However, the client library incorrectly handles these scenarios which results into these requests to be continuously retried. Now, to make it worse if SDK is configured to collect network requests errors and log them too, it actually makes situation worse - now on every failed request to `https://api.rollbar.com/api/1/item/` Rollbar SDK adds one more "error" to be tracked which results into queue of requests to grow which results into hitting project limits even faster.

Now if we go back to where the problem is. It is actually in `RollbarSender` class when it processes responses:

```
- (nullable NSHTTPURLResponse *)checkPayloadResponse:(NSURLResponse *)response
                                               error:(NSError *)error
                                                data:(NSData *)data
                               usingDeveloperOptions:(nonnull RollbarDeveloperOptions *)developerOptions {
    
    if (error) {
        [RollbarSender trace:@"There was an error reporting to Rollbar:"
                 withOptions:developerOptions];
        [RollbarSender trace:[NSString stringWithFormat:@"   Error: %@", [error localizedDescription]]
                 withOptions:developerOptions];
        return nil;
    }
    
    NSHTTPURLResponse* httpResponse = (NSHTTPURLResponse*)response;
    if (httpResponse && (200 == [httpResponse statusCode])) {
        [RollbarSender trace:[NSString stringWithFormat:@"OK response from Rollar: %@", httpResponse]
                 withOptions:developerOptions];
        return httpResponse;
    }

    [RollbarSender trace:@"There was a problem reporting to Rollbar:"
             withOptions:developerOptions];
    [RollbarSender trace:[NSString stringWithFormat:@"   Response: %@", response]
             withOptions:developerOptions];
    [RollbarSender trace:[NSString stringWithFormat:@"   Response data: %@", data]
             withOptions:developerOptions];
    //            [RollbarSender trace:[NSString stringWithFormat:@"   Response data: %@",
    //                                  [NSJSONSerialization JSONObjectWithData:data
    //                                                                  options:0
    //                                                                    error:nil]
    //                                 ]
    //                     withOptions:developerOptions];

    return nil;
}
```

As you can see when http code is not 200 function returns `nil`. Now when function returns `nil` all the downstream logic is failing to correctly process the http status code `429`:
- `postPayload...`  returns `nil`;
- `RollbarPayloadPostReply *reply = [RollbarPayloadPostReply replyFromHttpResponse:response];` creates a reply with status code `0`;
- `sendPayload:...` returns `reply` object with status code `0`;
- `[record recordPostReply:reply];` which should handle backoff logic is now working with a broken `reply` object and bypasses checks and guards and re-issues new request instantly;
- infinite loop until backend starts accepting requests again.

Now there is a bigger question. How to unblock our team and project? We obviously aren't ready to pay for all the errors which have now been generated on all the devices in the wild due to this error in Rollbar SDK. We also cannot force update all our clients due to business reasons and we don't want to drop all actually valid errors on the device.

**Comment by nekto-zum** [comment]
Any news on the fix for this?

**Comment by TheDevFactory** [comment]
@ExtremeMan can you please contact the Rollbar support team with your account slug and they will help you investigate this issue linked to this GitHub issue you logged here. The server side rate limit shoudl take over (rate limit set on your tokens) even if the client attempts to send more requests they will be dropped when they get to Rollbar so you should never have more errors than what your user rate limit is set to.

**Comment by ExtremeMan** [comment]
Yeah, but now when limit is raised Rollbar will log millions of those errors generated because of the bug in the Rollbar SDK which keeps sending retries over and over again because it cannot handle http error codes.

**Comment by ExtremeMan** [comment]
Ultimately library fails to handle any non-200 http status codes from Rollbar backend. Is Rollbar team planning to fix that or it is better to fork and fix myself or move to another provider? Just try to use broken token and you will see how bad it is.

Please, let me know as this issue affects all your customers and if you are slow to respond and fix critical issues, this is a good signal to keep in mind.

**Comment by ExtremeMan** [comment]
@TheDevFactory are there any updates on this issue?

**Comment by TheDevFactory** [comment]
@ExtremeMan The Rollbar SDK team is investigating this issue and it will be in the next set of design and implementation sprints to update and examine this behavior in the codebase.

**Comment by ExtremeMan** [comment]
is it safe to assume this won't be fixed?

**Comment by matux** [comment]
@ExtremeMan I'm looking into this right now.

**Comment by ExtremeMan** [comment]
thank you guys! let me know if you need more context or anything - happy to help

**Comment by rollbar-bborsits** [comment]
@ExtremeMan Apology for the delay, probably communication got stuck around this issue. We’ll let you know when the fix is out.

**Comment by matux** [comment]
Almost there @ExtremeMan 😄, first PR #276 is out, a second one will handle the case where were we want to drop rate limited occurrences as a default. Working on it right now.

Truly appreciate your patience!!!
