### ISSUE TITLE
DSYM / crash reporting requirements in 3.0?

### ISSUE THREAD

**Issue by lavenj** [rollbar/rollbar-apple#279]
Hi @matux - excited about the crash reporting updates in 3.0. Could you clarify the dsym upload requirements/steps for 3.x?

**Comment by rollbar-bborsits** [comment]
Hey @lavenj,

We'll redesign the dSYM management user flows in Q2 as we found a bunch of simplification possibilities. Up until it gets released, you can upload your dSYMs like below:

1. Go to the project setting page https://app.rollbar.com/a/<account_slug>/projects
2. Choose your Apple project https://rollbar.com/<account_slug>/<project_slug>/settings/general/
3. Go to *Symbol Mapping > dSYMs*
4. Choose your `.dSYM` file
5. Set 'Bundle identifier" (e.g., com.rollbar.apple.demo.swift)
6. Set "Bundle version" (Use the "Bundle version" from your plist which corresponds to the Build Number. This is not the Version Number found under the key "Bundle versions string, short" in your pslist. We use this to match up the dSYM with the same version of the code that caused the stack trace.)
7. Click upload. The upload is finished when the bar reaches the right side of the page.

You can upload your dSYMs via the API too: https://docs.rollbar.com/reference/upload-a-dsym-file

Let me know if the process worked for you.

Cheers,
Botond

**Comment by lavenj** [comment]
Good enough - same process as previously basically - looking forward to the q2 updates. Thanks for the quick answer!
