### ISSUE TITLE
String Encoding Error for ’ (forward tick character) (3.0.0)

### ISSUE THREAD

**Issue by lavenj** [rollbar/rollbar-apple#294]
Logging a message with a forward tick `’` shows up garbled, eg 

![image](https://github.com/rollbar/rollbar-apple/assets/1328671/efac6d5f-8fdf-453d-96d1-1d3f3a426ce6)

Simple to recreate by sending a string with that character.

A common example is the generic apple error description: "The operation couldn’t be completed"

**Comment by rollbar-bborsits** [comment]
Hey @lavenj, Thanks for reporting this issue. We may have an encoding issue. This looks like it is connected with #295. Let me bring this back to the devs.
