### ISSUE TITLE
Emojis are not rendering correctly in the Dashboard/items

### ISSUE THREAD

**Issue by alexoviedo-casumo** [rollbar/rollbar-apple#295]
**Describe the bug**
Hello!

We made the migration to the Apple SDK, and everything seems to be running smoothly in terms of configuration and sending logs. However, we've run into a minor issue with the Dashboard. It seems that we're no longer able to see the emojis we send from our codebase. It used to work perfectly before the migration.

If you have any ideas or suggestions about the issue, we'd really appreciate your help!

thank you!

**To Reproduce**
just send:

`   Rollbar.log(.error, message: "❌ Error", data: nil)
`
and then go to the dashboard/items.

**Expected behavior**

**This is how it worked before the migration:**

<img width="229" alt="Screenshot 2023-06-08 at 11 15 11" src="https://github.com/rollbar/rollbar-apple/assets/132347996/a86f14df-7225-45a0-85b2-75065b7e69a9">

**After the migration:**

<img width="237" alt="Screenshot 2023-06-08 at 11 14 07" src="https://github.com/rollbar/rollbar-apple/assets/132347996/4c44739d-cde5-45db-a72c-5d8394dc4815">

**Rollbar-Apple SDK version: 3.0.1**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: [e.g. macMini, iMac, iPhone, etc.]:mac m2 pro
 - OS: [e.g. iOS, macOS, etc]: macoss
 - OS version: 13.4
 
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: iPhone 8 plus
 - OS: [e.g. iOS8.1]: 16.5

**Comment by rollbar-bborsits** [comment]
Hey @alexoviedo-casumo, Thanks for reporting this issue. I understand that you used the rollbar-ios SDK previously, and now you migrated to the rollbar-apple SDK. This looks like to be an encoding error, indeed. Can you open a [support ticket](https://rollbar.com/contact/?inquiryType=Support) about this case? The information you shared here is perfect. Can you share links to the items in question? I don't want to discuss that info publicly. Thanks.

**Comment by matux** [comment]
I was able to fix the encoding issue (PR incoming), but it seems that, while unicode is now rendered fine in the web's occurrence details view, non-ASCII characters are being removed from the Item's title server-side.

I raised this with product to see whether this is being done on purpose, or if it's a bug.
