### ISSUE TITLE
Critical Flaw: Compiler Error Due to Name Ambiguity in KSCrash when compiling the SDK

### ISSUE THREAD

**Issue by rashadatjou** [rollbar/rollbar-apple#297]
**Describe the bug**
When compiling my framework with Rollbar-Apple, a compiler error occurs. The issue seems to be caused by KSCrash, exposing a class that has the same name as the module KSCrash. This name ambiguity leads to a compiler error, similar to the one listed in https://github.com/apple/swift/issues/64669.

**To Reproduce**
1. Add the Rollbar-Apple dependency to a Swift framework project.
2. Import Rollbar Notifier
3. Try to archive the framework.
The compiler error occurs.

**Expected behavior**
I expected the framework to compile successfully without errors, even when including Rollbar-Apple as a dependency.

**Screenshots**
<img width="1616" alt="Screenshot 2023-06-12 at 13 40 13" src="https://github.com/rollbar/rollbar-apple/assets/28106084/581bcbed-47b2-411b-922c-08e7af61a60f">

**Rollbar-Apple SDK version:** `3.0.0`

**Xcode Versions Used:** 
- `14.2`
- `14.3`
- `14.3.1`

**Swift Version Used:**
- `5.7`
- `5.8`

**Additional Context**
When trying to ignore this error with the `-no-verify-emitted-module-interface` compiler flag, the compiled .swiftinterface file ends up broken and unusable. This issue appears to be a limitation of the Swift compiler when a type has the same name as a module. I believe adjusting the naming in KSCrash to avoid this ambiguity could solve the issue.

**Comment by rollbar-bborsits** [comment]
Hey @rashadatjou, Thanks for reaching out. Really sorry to hear you're having issues with the Apple SDK. Let me take this to the devs and see what we can do.

**Comment by matux** [comment]
We're tracking this internally @ https://app.shortcut.com/rollbar/story/127332/unable-to-integrate-apple-sdk-to-frameworks.

**Comment by rashadatjou** [comment]
If you need a more detailed log from me, feel free to reach out on my email: rashadajtou[.]mehdi[@]gmail[.]com I would love to help out and get this bug sorted.

**Comment by rollbar-bborsits** [comment]
@rashadatjou Thanks; I appreciate your help. We're currently working on closing some Q2 initiatives, which require our absolute focus. We'll handle lower-severity bugs after we sorted out some high-priority projects.

**Comment by rashadatjou** [comment]
@rollbar-bborsits I do understand that. Unfortunately, We had to remove Rollbar from our project due to this issue and had to integrate another error tracking solution. As I appreciate the level of quality of this project (big props to the devs it is a beauty) We would reconsider integrating Rollbar again when this issue gets resolved. 

I will also try to integrate Rollbar by using the new type of Mergable frameworks that will ship with Xcode 15 as I would not need to integrate Rollbar as an Dynamic framework into my project.

**Comment by rollbar-bborsits** [comment]
@rashadatjou In the meantime, we picked up this issue again. I'll let you know when the fix is ready.

**Comment by rollbar-bborsits** [comment]
@rashadatjou We plan to release a new version that will fix your issue. Stay tuned ;)

**Comment by rashadatjou** [comment]
@rollbar-bborsits is the new version out perhaps?

**Comment by rollbar-bborsits** [comment]
@rashadatjou We plan to release the new version in the upcoming days. We ran into a bug during testing, so we want to fix that before the release. The SDK didn't handle the HTTP response codes accordingly, which led to queuing errors and repeated sends.

**Comment by rashadatjou** [comment]
@rollbar-bborsits thank you for the swift response. I am holding my fingers crossed 🤞 for the release. Wish the devs good luck from me!

**Comment by rollbar-bborsits** [comment]
We released the new version recently: https://github.com/rollbar/rollbar-apple/releases/tag/3.1.0
