### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by LittIe-ma** [rollbar/rollbar-apple#342]
Do you have any plans to add a Privacy Manifest to this library?

Is this library not required to be supported?

Thank you very much!

**Comment by igorstojanovicvicert** [comment]
Is there any update about adding the Privacy Manifest?
Thank you.

**Comment by zdavis-rollbar** [comment]
We are currently working on it and should have it ready in the next few minutes.

**Comment by zdavis-rollbar** [comment]
@igorstojanovicvicert we have released the latest version 3.3.0 with the Privacy manifest.
