### ISSUE TITLE
Short Documentation about the Sub-Libraries 

### ISSUE THREAD

**Issue by martnst** [rollbar/rollbar-apple#46]
I understand that version 2.0 is still in progress, so you may simply take this ticket as a reminder. 🙂 

As off now I was not able to find any documentation explaining the purpose of each of the Library that this projects comes with. I personally find it hard to pick which Products/Libraries I need for my project. For example, I was wondering about `RollbarKSCrash` vs. `RollbarPLCrashReporter`. Or do I always need `RollbarCommon` as a base library for all others. For now I simply went with my gut feeling. 

![image](https://user-images.githubusercontent.com/3084607/108595713-b3d52d80-7381-11eb-84c8-00647713fdce.png)

Again since 2.0 appears not officially done yet, I understand that such docs may not yet exist on Rollbar's own hosted docs over here: https://docs.rollbar.com/docs/apple
However, I think a simple table with a short description for each of the Libraries could be included in the README of this repo sooner than later. Especially as the README is versioned in branches as well, it's easy to provide sth. ahead of time. 

FYI: I also compared the Pod Specs and could not find any distinction other than technical ones. 
![image](https://user-images.githubusercontent.com/3084607/108596002-6c02d600-7382-11eb-9859-7773c9f5b77c.png)

Bests, 
Martin

**Comment by martnst** [comment]
Okay, by now I realized that I should pick one crash reporter being either [KSCrash](https://github.com/kstenerud/KSCrash) or  [PLCrashReporter ](https://github.com/microsoft/plcrashreporter) to go along with Rollbar. I am right?

**Comment by akornich** [comment]
@martnst , absolutely correct! We offer 2 optional crash reporting alternatives - one based on KSCrash and another one based on PLCrashReporter. Each package (RollbarKSCrash or RollbarPLCrashReporter) implements its own crash report collector adapter to a corresponding third-party crash reporter.
A collector is optional and can be supplied into a notifier (RollbarLogger) initializer along with the required RollbarConfig instance.
RollbarNotifier is the package that implements the RollbarLogger (i.e. Notifier) - that is the thing that supports a lot of configurational options and allows to capture, package, and forward (to the preconfigured Rollbar Project on rollbar.com) exceptions, errors, log messages, telemetry, and custom data.
RollbarDeploys is the package that should be used, for example by your CI Release pipeline, to track/manage your application releases/deployments so they are reported to the Rollbar Project and Rollbar would correlate the incoming payloads with specific deployment instance.
RollbarCommon is just a shared package with types used by any of the other packages as well as some potentially useful public utility classes that you may find useful.
We definitely will start populating the SDK documentation anytime soon, once the timeframe for going beta is decided.
@martnst , thanks a lot for your effort and curiosity to start using the SDK even in its alpha phase. Your feedback is very valuable to us and much appreciated.
Best regards,
- Andrey

**Comment by akornich** [comment]
Updated with the module/package overview: 
https://docs.rollbar.com/docs/apple#sdk-modulespackages-overview
and usage of crash collectors:
https://docs.rollbar.com/docs/apple#optionally-define-a-crash-report-collector-instance
