### ISSUE TITLE
Ability to Disable RollbarSDK Logs 

### ISSUE THREAD

**Issue by martnst** [rollbar/rollbar-apple#47]
I get logs about processing items every second. 

```logs
… [Rollbar] Checking items...
… [Rollbar] Processing saved items: no queued items in the file!
```

I did check the code and found two things. 

First there is no option to disables the logs via `RollbarConfig`. 

https://github.com/rollbar/rollbar-apple/blob/a085fecdf7d7cd2bd51be7835bc55cff2b54d2fb/RollbarCommon/Sources/RollbarCommon/RollbarSdkLog.m#L6-L11

Second I may lower the rate of these logs like by setting `maximumReportsPerMinute`. However, this does not turn the logs off. It only makes them less annoying. 

```swift
let config = RollbarConfig()
config.destination.accessToken = MyConfig.rollbarToken
config.destination.environment = MyConfig.isDebug ? "development" : "production"
config.loggingOptions.maximumReportsPerMinute = 1
Rollbar.initWithConfiguration(config)
```

Also, you may actually don't want to lower the rate to check for items. 

Best, Martin

**Comment by akornich** [comment]
@martnst , good point! Yes, we already have this work item in our internal backlog. I'll try to add it by the time we promote the SDK to beta.
Best regards,
- Andrey
