### ISSUE TITLE
It is impossible to import the SPM package into the project.

### ISSUE THREAD

**Issue by xexuew** [rollbar/rollbar-apple#63]
**Describe the bug**
It is impossible to install the package for a new project with SwiftUI, using Swift Package Manager.

**To Reproduce**
1. Choose package repository: https://github.com/rollbar/rollbar-apple.git
2. Select Rules -> Branch -> master
3. See Screenshot 1. "
Showing All Messages
Source files for target RollbarSwift should be located under 'Sources/RollbarSwift', or a custom sources path can be set with the 'path' property in Package.swift"
4. Can't install.

1. Choose package repository: https://github.com/rollbar/rollbar-apple.git
2. Select Rules -> Up to mayor -> 1.12.9 
3. Installation completed successfully.
4. This error appears: "Could not build Objective-C module 'Rollbar'.
5.  Annexed:
5.1 Change branch to master.
5.2 Correct installation.
5.3 Directories missing.

**Expected behavior**
Successfully import the package into the project.

**Screenshots**
Screenshot1:
<img width="663" alt="Captura de pantalla 2021-04-06 a las 20 23 29" src="https://user-images.githubusercontent.com/7280807/113761038-46097900-9717-11eb-8ac3-40140bc83615.png">

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[X] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: MacBook Pro
 - OS: macOS
 - OS version: 10.15.4 Catalina
 
**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS14.4

**Additional context**
Thanks in advance.

**Comment by akornich** [comment]
@xexuew , thanks for reporting the issue! 
I just made a change to the package manifest. Please, make sure you have the following settings:
![Screen Shot 2021-04-06 at 16 28 57](https://user-images.githubusercontent.com/1753993/113791868-73dfc500-96f9-11eb-8fee-4db07539f0ca.png)
Then, go to Xcode File menu -> Swift Packages -> Update to Latest Package Versions.
Then, make a clean build.
You should be fine at this point.

**Comment by RickPasveer** [comment]
I'm using the master branch but i'm not receiving all the package sources.

I'm using the **master** branch on https://github.com/rollbar/rollbar-apple/

<img width="285" alt="Schermafbeelding 2021-04-07 om 14 23 21" src="https://user-images.githubusercontent.com/6460870/113865943-02614e80-97ad-11eb-86a2-93d74ca9c408.png">

**Comment by xexuew** [comment]
@akornich Thanks for the reply.

I have managed to add it to the project and get it working without any problems.

You can close the issue.
Thanks again

**Comment by akornich** [comment]
@RickPasveer , it looks like an Xcode issue. If you right-click on the package and select Show in Finder, you will see that all the source code folders/files of the package are there and it all can be imported/used successfully.

**Comment by akornich** [comment]
@xexuew , thanks for the confirmation! Can we close this issue?
