### ISSUE TITLE
Excessive logging of »Processing saved items«

### ISSUE THREAD

**Issue by arthurschiller** [rollbar/rollbar-apple#64]
**Describe the bug**
After initializing the library I am getting a console log roughly every 0.5 seconds: »**[Rollbar] Processing saved items: no queued items in the file!**« which is kind of polluting my other logging.
I assume this is normal, even though I'm wondering why these checks are performed so often?
_**Setting config.developerOptions.suppressSdkInfoLogging allowed my to suppress this.**_

**To Reproduce**
1. Initialize the SDK with access token
2. Look into Xcode console

**Expected behavior**
I personally would expected that this kind of logging only occurs if explicitly being enabled.
If logging occurs by default it should be less obstrusive.

**Screenshots**
![rollbar-logging](https://user-images.githubusercontent.com/3637723/114170666-8cd3ba80-9933-11eb-8995-4592e81cba57.jpg)

**Rollbar-Apple SDK version: v2.0.0-beta8**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[X] Swift
[] Other: 

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.4.1

**Comment by akornich** [comment]
@arthurschiller , you can disable this output by explicitly setting  the following property on the RollbarConfig instance you used to configure the SDK with:
`config.developerOptions.suppressSdkInfoLogging = YES;`

**Comment by arthurschiller** [comment]
Hi @akornich yes I figured that out. Though I think this should be the default if this kind of logging always takes place, as it essentially clutters the console. Thanks!

**Comment by akornich** [comment]
@arthurschiller , yes, our idea is that the log entries are useful for the first-time SDK integrators, that is why we keep it ON by default. As you can see, it is very easy to turn it off.
Best regards! Let me know if you need more help with the SDK.
