### ISSUE TITLE
App terminated due to signal 5 instantiating RollbarPLCrashCollector

### ISSUE THREAD

**Issue by peakresponseinc** [rollbar/rollbar-apple#66]
**Describe the bug**
App will terminate with the following message:

`Message from debugger: Terminated due to signal 5`

This occurs on the line that instantiates a RollbarPLCrashCollector:

`let crashCollector = RollbarPLCrashCollector()`

**To Reproduce**
1. Add RollbarNotifier, RollbarPLCrashReporter, RollbarSwift cocopods v2.0.0-beta9 to Podfile, install
2. Add sample Swift code from docs into AppDelegate:
```
import RollbarNotifier
import RollbarPLCrashReporter
...
func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    let config = RollbarConfig()
    config.destination.accessToken = "..."
    config.destination.environment = "..."
    let crashCollector = RollbarPLCrashCollector()
    Rollbar.initWithConfiguration(config, crashCollector: crashCollector)
    ....
}
```

**Expected behavior**
App will launch successfully.

**Screenshots**
N/A

**Rollbar-Apple SDK version: v2.0.0-beta9**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: MacBook Pro 16"/iOS Simulator iPhone 12
 - OS: iOS
 - OS version: 14.3

**Comment by akornich** [comment]
@peakresponseinc , thanks for reporting the issue! Does it happen starting with v2.0.0-beta9? Did you upgrade from older version that worked?
Also, did you try the SDK integration via Swift Package Manager (it is our recommended SDK integration route since it is much less intrusive than Cocoapods)?

**Comment by peakresponseinc** [comment]
This is my first integration test, so I was not upgrading from a prior version. I can try to pin to an older version in my Podfile to see if it works...

However, since I have an existing project that is already set up with Cocoapods, I won't be evaluating using Swift Package Manager at this time... I may just switch to the older Rollbar iOS SDK instead...

**Comment by akornich** [comment]
@peakresponseinc , thanks for the prompt reply! Yes, please, try pinning to an older release. If that does not unblock you, you can for now pass `nil` instead of the collector instance. The SDK would operate without picking up crash reports with the rest of its functionality available. I'll try to see what's happening with the PLC collector sometime tomorrow.

**Comment by peakresponseinc** [comment]
Just FYI, I could not find a prior beta version that could properly resolve dependencies- looking at the release notes, it seems like fixing the podspecs were the changes, so I could not test an older version.

**Comment by akornich** [comment]
@peakresponseinc , thanks for the update! I think I found a possible cause of the issue. I'll test it more tomorrow and will make a new release if it all looks good. Stay tuned!
