### ISSUE TITLE
Excessive Console Debug Printing

### ISSUE THREAD

**Issue by jsahoo** [rollbar/rollbar-apple#69]
**Describe the bug**
The following is printed every second:
```
2021-04-15 14:23:39.459637-0700 My Project[24197:8393522] [Rollbar] Checking items...
2021-04-15 14:23:39.461118-0700 My Project24197:8393522] [Rollbar] Processing saved items: no queued items in the file!
```

**To Reproduce**
1. Initialize Rollbar:
```
        rollbarConfig = RollbarConfig()
        rollbarConfig.destination.accessToken = accessToken
        Rollbar.initWithConfiguration(rollbarConfig, crashCollector: nil)
```

**Expected behavior**
The above mentioned logs should not be printed

**Rollbar-Apple SDK version: v...**
Latest `master` (commit 6fa0b1d3e7427a168b6e3cf5527dbefb075527ff)

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: iPhone 11 Pro
 - OS: iOS 
 - OS version: 14.4.1

**Comment by jsahoo** [comment]
Just discovered I can suppress the logging with:
```
rollbarConfig.developerOptions.suppressSdkInfoLogging = true
```
which is great, although not sure if that's the best option as it'll silence (presumably) _all_ SDK info logging, not just the "Checking items" and "Processing saved items" ones. Is it intentional behavior for "Checking items" and "Processing saved items" to print every second?

**Comment by akornich** [comment]
@jsahoo , please, set `developerOptions.suppressSdkInfoLogging` flag on the RollbarConfig instance to suppress the entries.

**Comment by akornich** [comment]
it suppresses the periodic "ticking" - all the other ones (accidental - so to speak) are enabled.
