### ISSUE TITLE
SPM - Please tag versions using correct Semantic Versioning

### ISSUE THREAD

**Issue by jsahoo** [rollbar/rollbar-apple#70]
**Describe the bug**
Unable to add `Rollbar-Apple` as a dependency using Swift Package Manager due to the version numbers not being in the correct format. From what I gathered from [this Ray Wenderlich article](https://www.raywenderlich.com/1993018-an-introduction-to-swift-package-manager#toc-anchor-005), beta versioning should have the following format: `1.1.3-beta.4`. The existing tags have the following format: `v2.0.0-beta9`.

**To Reproduce**
1. Add the following to your `Package.swift`'s list of dependencies:
```
.package(name: "RollbarSDK", url: "https://github.com/rollbar/rollbar-apple.git", from: "v2.0.0-beta9")
```

**Expected behavior**
SPM should not fail

**Rollbar-Apple SDK version: v...**
`v2.0.0-beta9`

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other:

**Comment by akornich** [comment]
@jsahoo , good observation. I only stay on the `master` branch SPM semantics for my needs. You can do the same for now (using branch instead of tag when referencing SPM dependencies on the SDK). I'll be issuing a new release today/tomorrow and will follow your advice when tagging it. Thank you!

**Comment by jsahoo** [comment]
No problem! I'll stick to `.revision("6fa0b1d3e7427a168b6e3cf5527dbefb075527ff")` until then 🙂

**Comment by akornich** [comment]
yes, that should work as well.

**Comment by akornich** [comment]
@jsahoo , can we close it now? or you are still having issues integrating via SPM?

**Comment by jsahoo** [comment]
Actually having another issue now.. when I add the following to my dependencies list, Xcode gets stuck indefinitely "Updating rollbar-apple" and basically cripples Xcode completely (can't stop, can't even quit, only force quit)

```
.package(name: "RollbarSDK", url: "https://github.com/rollbar/rollbar-apple.git", .upToNextMajor(from: "2.0.0-beta.14"))
```

![image](https://user-images.githubusercontent.com/6937424/116174838-0f929e80-a6c4-11eb-8760-ca526ce470be.png)

Switching back to `.branch("master")` or `.revision("6fa0b1d3e7427a168b6e3cf5527dbefb075527ff")` resolves the problem

**Comment by akornich** [comment]
@jsahoo , i assume this one is also resolved by now. Can we close it?

**Comment by jsahoo** [comment]
Yep! Works great now!
