### ISSUE TITLE
Rollbar* pods 2.0.0-beta.10 not all published

### ISSUE THREAD

**Issue by francisli** [rollbar/rollbar-apple#72]
**Describe the bug**
The latest published version of the Rollbar* pods are inconsistent:

RollbarSwift 2.0.0-beta9
RollbarPLCrashReporter 2.0.0-beta9
RollbarNotifier 2.0.0-beta9
RollbarDeploys 2.0.0-beta.10
RollbarCommon 2.0.0-beta.10

As a result, it is not possible to reference the latest release across all the dependencies

**Screenshots**

<img width="569" alt="Screen Shot 2021-04-16 at 5 08 12 PM" src="https://user-images.githubusercontent.com/140766/115095566-97afc180-9ed6-11eb-854f-338b63bed559.png">

**Rollbar-Apple SDK version: v2.0.0-beta.10*

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other:

**Comment by akornich** [comment]
correct. trying to figure out why now the rest of pods fail validation during publishing...
