### ISSUE TITLE
RollbarNotifier build fails in Release mode

### ISSUE THREAD

**Issue by francisli** [rollbar/rollbar-apple#80]
**Describe the bug**
When archiving a Release build of my app with the RollbarNotifier included, the build fails.

**To Reproduce**
1. Create an app with RollbarNotifier, RollbarSwift, RollbarPLCrashReporter integrated using Cocoapods
2. Choose Product -> Archive to build a Release version
3. Observe ~20 errors reported from the build in the RollbarNotifier project

**Screenshots**
A couple of the errors:

```
❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:14:1: unknown type name 'NS_ASSUME_NONNULL_BEGIN'

NS_ASSUME_NONNULL_BEGIN
               ^~



❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:32: declaration of 'NSArray' must be imported from module 'Foundation.NSUserActivity' before it is required

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
^



❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:39: expected member name or ';' after declaration specifiers

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
                ^



❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:1: property requires fields to be named

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
                               ~~~~~~~^



❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:39: expected ';' at end of declaration list

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
^                              ~~~~~~~



❌  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:62: expected '>'

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
                                      ^



⚠️  /Users/francisli/Library/Developer/Xcode/DerivedData/Triage-aygvbqiqsqurtoehmxzzfjdwzaqi/Build/Intermediates.noindex/ArchiveIntermediates/Triage/BuildProductsPath/Release-iphoneos/RollbarNotifier/RollbarNotifier.framework/./Headers/RollbarTrace.h:22:39: protocol has no object type specified; defaults to qualified 'id'

@property (nonatomic, nonnull) NSArray<RollbarCallStackFrame *> *frames;
``` 

**Rollbar-Apple SDK version: v2.0.0-beta.14*

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Additional context**

Might be related to somehow not properly importing Foundation in the Release...?

https://stackoverflow.com/questions/54999099/unknown-type-name-ns-assume-nonnull-begin

**Comment by akornich** [comment]
@francisli , please make sure you clear the Derived data, close and reopen Xcode and make an absolutely clean build.

**Comment by francisli** [comment]
@akornich per your suggestion, I just did a Product > Clean Build Folder, then completely quit Xcode, manually deleted the entire Derived Data folder, restarted Xcode, and performed another Product > Archive, and _still_ received the same errors again.

I then did a Product > Build to compile a Debug build, and it completed successfully.

**Comment by akornich** [comment]
@francisli , that is great news! What about the Archive/Release build that you mentioned initially?

**Comment by akornich** [comment]
That is interesting. To my best knowledge, we do not differentiate between Debug and Release build settings in the podspecs. I'll try to repro the issue myself (probably tomorrow). Meantime, can you switch to SwiftPM based integration instead of Cocoapods? BTW, is it a recent SDK release issue or did you observe a similar problem with older releases?

**Comment by akornich** [comment]
@francisli , are you still experiencing the problem?

**Comment by francisli** [comment]
@akornich I see that there have been newer releases since I last tested, I'll need to update to the latest and try again, and will let you know...

**Comment by akornich** [comment]
@francisli , yes, please, try 2.0.0-beta.21 that was just released.

**Comment by francisli** [comment]
@akornich I just updated to 2.0.0-beta.22 and, unfortunately, it still fails to build in Release mode...

I can't spend any more time on this at the moment, but after next week I may have time to poke into your project and see what's going on...

**Comment by francisli** [comment]
@akornich apologies for a long absence, but I did revisit this and just did a complete clean/delete derived data/rebuild, and was able to successfully build a release version with the latest 2.0.0-beta.22, so I think this issue can be closed now, I must have missed a cleanup step in my first test last month...!

**Comment by akornich** [comment]
@francisli , thanks for the update.
