### ISSUE TITLE
SPM - Resolving Package Graph Failed

### ISSUE THREAD

**Issue by jsahoo** [rollbar/rollbar-apple#81]
**Describe the bug**
<img width="829" alt="Screen Shot 2021-04-26 at 7 34 05 PM" src="https://user-images.githubusercontent.com/6937424/116176264-baa45780-a6c6-11eb-9893-f1b006e108f9.png">

**To Reproduce**
1. Add rollbar-apple as a dependency

**Rollbar-Apple SDK version: v...**
2.0.0-beta.14

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[x] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: iPhone 11 Pro
 - OS: iOS
 - OS version: 14.5

**Additional context**
Xcode 12.5
Note that version 2.0.0-beta.13 works fine

**Comment by jsahoo** [comment]
Thanks @akornich!

**Comment by akornich** [comment]
@jsahoo , you are welcome! Let me know if you run into any other issues. Also, general feedback on  SDK (its design, API, quality, performance) is very welcome. And of cause, any suggestion for a new feature or improving an existing one is welcome.
